id: A0ABE91EF
title: 'Vajrakīla Prayer: A Rain of Accomplishments'
type: translation
pechas:
- IBFB09447
- I1B2945D0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:36:59.616979
  last_modified_at: 2023-01-04 11:36:59.616990
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IBFB09447/D446: 9CE7
  I1B2945D0/66C2: 9CE7
